// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

// Tabla principal que almacena los equipos del sistema
type Equipo struct {
	// Identificador único autoincremental del equipo
	ID int64 `json:"id"`
	// Nombre único del club o entidad deportiva
	Nombre string `json:"nombre"`
	// Esquema táctico asignado (ej. 4-3-3, 4-4-2)
	FormacionActual string         `json:"formacion_actual"`
	EscudoUrl       sql.NullString `json:"escudo_url"`
}
