// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createEquipo = `-- name: CreateEquipo :one
INSERT INTO equipos (
    nombre,
    formacion_actual,
    escudo_url
) VALUES (
    $1, $2, $3
)
RETURNING id, nombre, formacion_actual, escudo_url
`

type CreateEquipoParams struct {
	Nombre          string         `json:"nombre"`
	FormacionActual string         `json:"formacion_actual"`
	EscudoUrl       sql.NullString `json:"escudo_url"`
}

func (q *Queries) CreateEquipo(ctx context.Context, arg CreateEquipoParams) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, createEquipo, arg.Nombre, arg.FormacionActual, arg.EscudoUrl)
	var i Equipo
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FormacionActual,
		&i.EscudoUrl,
	)
	return i, err
}

const deleteEquipo = `-- name: DeleteEquipo :exec
DELETE FROM equipos
WHERE id = $1
`

func (q *Queries) DeleteEquipo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEquipo, id)
	return err
}

const getEquipoByID = `-- name: GetEquipoByID :one
SELECT 
    id,
    nombre,
    formacion_actual,
    escudo_url
FROM equipos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEquipoByID(ctx context.Context, id int64) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, getEquipoByID, id)
	var i Equipo
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FormacionActual,
		&i.EscudoUrl,
	)
	return i, err
}

const listEquipos = `-- name: ListEquipos :many
SELECT 
    id,
    nombre,
    formacion_actual,
    escudo_url
FROM equipos
ORDER BY nombre ASC
`

func (q *Queries) ListEquipos(ctx context.Context) ([]Equipo, error) {
	rows, err := q.db.QueryContext(ctx, listEquipos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipo
	for rows.Next() {
		var i Equipo
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.FormacionActual,
			&i.EscudoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipo = `-- name: UpdateEquipo :one
UPDATE equipos
SET 
    nombre = $1,
    formacion_actual = $2,
    escudo_url = $3
WHERE id = $4
RETURNING id, nombre, formacion_actual, escudo_url
`

type UpdateEquipoParams struct {
	Nombre          string         `json:"nombre"`
	FormacionActual string         `json:"formacion_actual"`
	EscudoUrl       sql.NullString `json:"escudo_url"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateEquipo(ctx context.Context, arg UpdateEquipoParams) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, updateEquipo,
		arg.Nombre,
		arg.FormacionActual,
		arg.EscudoUrl,
		arg.ID,
	)
	var i Equipo
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FormacionActual,
		&i.EscudoUrl,
	)
	return i, err
}
