// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Equipo struct {
	ID              int32          `json:"id"`
	Nombre          string         `json:"nombre"`
	FormacionActual string         `json:"formacion_actual"`
	EscudoUrl       sql.NullString `json:"escudo_url"`
	MejorJugador    sql.NullInt32  `json:"mejor_jugador"`
	Valoracion      int16          `json:"valoracion"`
	PosicionTabla   int16          `json:"posicion_tabla"`
}

type Jugadore struct {
	ID              int32          `json:"id"`
	EquipoID        int32          `json:"equipo_id"`
	Nombre          string         `json:"nombre"`
	Posicion        string         `json:"posicion"`
	FechaNacimiento time.Time      `json:"fecha_nacimiento"`
	MediaGeneral    int16          `json:"media_general"`
	Altura          string         `json:"altura"`
	Ritmo           int16          `json:"ritmo"`
	Tiro            int16          `json:"tiro"`
	Pase            int16          `json:"pase"`
	Regate          int16          `json:"regate"`
	Defensa         int16          `json:"defensa"`
	Fisico          int16          `json:"fisico"`
	Goles           int16          `json:"goles"`
	Asistencias     int16          `json:"asistencias"`
	FotoUrl         sql.NullString `json:"foto_url"`
}

type Partido struct {
	ID                int32     `json:"id"`
	EquipoLocalID     int32     `json:"equipo_local_id"`
	EquipoVisitanteID int32     `json:"equipo_visitante_id"`
	GolesLocal        int16     `json:"goles_local"`
	GolesVisitante    int16     `json:"goles_visitante"`
	Fecha             time.Time `json:"fecha"`
	Estado            string    `json:"estado"`
}
