// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createEquipo = `-- name: CreateEquipo :one
INSERT INTO "equipos" (
    "nombre",
    "formacion_actual",
    "escudo_url",
    "valoracion",
    "posicion_tabla"
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, nombre, formacion_actual, escudo_url, mejor_jugador, valoracion, posicion_tabla
`

type CreateEquipoParams struct {
	Nombre          string         `json:"nombre"`
	FormacionActual string         `json:"formacion_actual"`
	EscudoUrl       sql.NullString `json:"escudo_url"`
	Valoracion      int16          `json:"valoracion"`
	PosicionTabla   int16          `json:"posicion_tabla"`
}

func (q *Queries) CreateEquipo(ctx context.Context, arg CreateEquipoParams) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, createEquipo,
		arg.Nombre,
		arg.FormacionActual,
		arg.EscudoUrl,
		arg.Valoracion,
		arg.PosicionTabla,
	)
	var i Equipo
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FormacionActual,
		&i.EscudoUrl,
		&i.MejorJugador,
		&i.Valoracion,
		&i.PosicionTabla,
	)
	return i, err
}

const createJugador = `-- name: CreateJugador :one
INSERT INTO "jugadores" (
    "equipo_id",
    "nombre",
    "posicion",
    "fecha_nacimiento",
    "media_general",
    "altura",
    "ritmo",
    "tiro",
    "pase",
    "regate",
    "defensa",
    "fisico",
    "foto_url"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)

RETURNING id, equipo_id, nombre, posicion, fecha_nacimiento, media_general, altura, ritmo, tiro, pase, regate, defensa, fisico, goles, asistencias, foto_url
`

type CreateJugadorParams struct {
	EquipoID        int32          `json:"equipo_id"`
	Nombre          string         `json:"nombre"`
	Posicion        string         `json:"posicion"`
	FechaNacimiento time.Time      `json:"fecha_nacimiento"`
	MediaGeneral    int16          `json:"media_general"`
	Altura          string         `json:"altura"`
	Ritmo           int16          `json:"ritmo"`
	Tiro            int16          `json:"tiro"`
	Pase            int16          `json:"pase"`
	Regate          int16          `json:"regate"`
	Defensa         int16          `json:"defensa"`
	Fisico          int16          `json:"fisico"`
	FotoUrl         sql.NullString `json:"foto_url"`
}

func (q *Queries) CreateJugador(ctx context.Context, arg CreateJugadorParams) (Jugadore, error) {
	row := q.db.QueryRowContext(ctx, createJugador,
		arg.EquipoID,
		arg.Nombre,
		arg.Posicion,
		arg.FechaNacimiento,
		arg.MediaGeneral,
		arg.Altura,
		arg.Ritmo,
		arg.Tiro,
		arg.Pase,
		arg.Regate,
		arg.Defensa,
		arg.Fisico,
		arg.FotoUrl,
	)
	var i Jugadore
	err := row.Scan(
		&i.ID,
		&i.EquipoID,
		&i.Nombre,
		&i.Posicion,
		&i.FechaNacimiento,
		&i.MediaGeneral,
		&i.Altura,
		&i.Ritmo,
		&i.Tiro,
		&i.Pase,
		&i.Regate,
		&i.Defensa,
		&i.Fisico,
		&i.Goles,
		&i.Asistencias,
		&i.FotoUrl,
	)
	return i, err
}

const createPartido = `-- name: CreatePartido :one
INSERT INTO "partidos" (
    "equipo_local_id",
    "equipo_visitante_id",
    "fecha",
    "estado"
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, fecha, estado
`

type CreatePartidoParams struct {
	EquipoLocalID     int32     `json:"equipo_local_id"`
	EquipoVisitanteID int32     `json:"equipo_visitante_id"`
	Fecha             time.Time `json:"fecha"`
	Estado            string    `json:"estado"`
}

func (q *Queries) CreatePartido(ctx context.Context, arg CreatePartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, createPartido,
		arg.EquipoLocalID,
		arg.EquipoVisitanteID,
		arg.Fecha,
		arg.Estado,
	)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
		&i.Estado,
	)
	return i, err
}

const deleteEquipo = `-- name: DeleteEquipo :exec
DELETE FROM "equipos"
WHERE "id" = $1
`

func (q *Queries) DeleteEquipo(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEquipo, id)
	return err
}

const deleteJugador = `-- name: DeleteJugador :exec
DELETE FROM "jugadores"
WHERE "id" = $1
`

func (q *Queries) DeleteJugador(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteJugador, id)
	return err
}

const deletePartido = `-- name: DeletePartido :exec
DELETE FROM "partidos"
WHERE "id" = $1
`

func (q *Queries) DeletePartido(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePartido, id)
	return err
}

const getEquipo = `-- name: GetEquipo :one
SELECT id, nombre, formacion_actual, escudo_url, mejor_jugador, valoracion, posicion_tabla FROM "equipos"
WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetEquipo(ctx context.Context, id int32) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, getEquipo, id)
	var i Equipo
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FormacionActual,
		&i.EscudoUrl,
		&i.MejorJugador,
		&i.Valoracion,
		&i.PosicionTabla,
	)
	return i, err
}

const getJugador = `-- name: GetJugador :one
SELECT id, equipo_id, nombre, posicion, fecha_nacimiento, media_general, altura, ritmo, tiro, pase, regate, defensa, fisico, goles, asistencias, foto_url FROM "jugadores"
WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetJugador(ctx context.Context, id int32) (Jugadore, error) {
	row := q.db.QueryRowContext(ctx, getJugador, id)
	var i Jugadore
	err := row.Scan(
		&i.ID,
		&i.EquipoID,
		&i.Nombre,
		&i.Posicion,
		&i.FechaNacimiento,
		&i.MediaGeneral,
		&i.Altura,
		&i.Ritmo,
		&i.Tiro,
		&i.Pase,
		&i.Regate,
		&i.Defensa,
		&i.Fisico,
		&i.Goles,
		&i.Asistencias,
		&i.FotoUrl,
	)
	return i, err
}

const getMejorJugadorByEquipo = `-- name: GetMejorJugadorByEquipo :one
SELECT id, equipo_id, nombre, posicion, fecha_nacimiento, media_general, altura, ritmo, tiro, pase, regate, defensa, fisico, goles, asistencias, foto_url FROM "jugadores"
WHERE "equipo_id" = $1
ORDER BY "media_general" DESC, "id" ASC
LIMIT 1
`

func (q *Queries) GetMejorJugadorByEquipo(ctx context.Context, equipoID int32) (Jugadore, error) {
	row := q.db.QueryRowContext(ctx, getMejorJugadorByEquipo, equipoID)
	var i Jugadore
	err := row.Scan(
		&i.ID,
		&i.EquipoID,
		&i.Nombre,
		&i.Posicion,
		&i.FechaNacimiento,
		&i.MediaGeneral,
		&i.Altura,
		&i.Ritmo,
		&i.Tiro,
		&i.Pase,
		&i.Regate,
		&i.Defensa,
		&i.Fisico,
		&i.Goles,
		&i.Asistencias,
		&i.FotoUrl,
	)
	return i, err
}

const getPartido = `-- name: GetPartido :one
SELECT id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, fecha, estado FROM "partidos"
WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetPartido(ctx context.Context, id int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getPartido, id)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
		&i.Estado,
	)
	return i, err
}

const getUltimoPartidoByEquipo = `-- name: GetUltimoPartidoByEquipo :one
SELECT id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, fecha, estado FROM "partidos"
WHERE "equipo_local_id" = $1 OR "equipo_visitante_id" = $1
ORDER BY "fecha" DESC, "id" DESC
LIMIT 1
`

func (q *Queries) GetUltimoPartidoByEquipo(ctx context.Context, equipoLocalID int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getUltimoPartidoByEquipo, equipoLocalID)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
		&i.Estado,
	)
	return i, err
}

const getUltimoPartidoConDetalleByEquipo = `-- name: GetUltimoPartidoConDetalleByEquipo :one
SELECT 
    p.id,
    p.fecha,
    p.estado,
    p.goles_local,
    p.goles_visitante,
    el.id AS local_id,
    el.nombre AS local_nombre,
    el.escudo_url AS local_escudo,
    ev.id AS visitante_id,
    ev.nombre AS visitante_nombre,
    ev.escudo_url AS visitante_escudo
FROM "partidos" p
JOIN "equipos" el ON p."equipo_local_id" = el."id"
JOIN "equipos" ev ON p."equipo_visitante_id" = ev."id"
WHERE p."equipo_local_id" = $1 OR p."equipo_visitante_id" = $1
ORDER BY p."fecha" DESC, p."id" DESC
LIMIT 1
`

type GetUltimoPartidoConDetalleByEquipoRow struct {
	ID              int32          `json:"id"`
	Fecha           time.Time      `json:"fecha"`
	Estado          string         `json:"estado"`
	GolesLocal      int16          `json:"goles_local"`
	GolesVisitante  int16          `json:"goles_visitante"`
	LocalID         int32          `json:"local_id"`
	LocalNombre     string         `json:"local_nombre"`
	LocalEscudo     sql.NullString `json:"local_escudo"`
	VisitanteID     int32          `json:"visitante_id"`
	VisitanteNombre string         `json:"visitante_nombre"`
	VisitanteEscudo sql.NullString `json:"visitante_escudo"`
}

func (q *Queries) GetUltimoPartidoConDetalleByEquipo(ctx context.Context, equipoLocalID int32) (GetUltimoPartidoConDetalleByEquipoRow, error) {
	row := q.db.QueryRowContext(ctx, getUltimoPartidoConDetalleByEquipo, equipoLocalID)
	var i GetUltimoPartidoConDetalleByEquipoRow
	err := row.Scan(
		&i.ID,
		&i.Fecha,
		&i.Estado,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.LocalID,
		&i.LocalNombre,
		&i.LocalEscudo,
		&i.VisitanteID,
		&i.VisitanteNombre,
		&i.VisitanteEscudo,
	)
	return i, err
}

const getUltimoPartidoFinalizadoByEquipo = `-- name: GetUltimoPartidoFinalizadoByEquipo :one
SELECT id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, fecha, estado FROM "partidos"
WHERE ("equipo_local_id" = $1 OR "equipo_visitante_id" = $1)
  AND "estado" = 'FINALIZADO'
ORDER BY "fecha" DESC, "id" DESC
LIMIT 1
`

func (q *Queries) GetUltimoPartidoFinalizadoByEquipo(ctx context.Context, equipoLocalID int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getUltimoPartidoFinalizadoByEquipo, equipoLocalID)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
		&i.Estado,
	)
	return i, err
}

const listEquipos = `-- name: ListEquipos :many
SELECT id, nombre, formacion_actual, escudo_url, mejor_jugador, valoracion, posicion_tabla FROM "equipos"
ORDER BY "posicion_tabla" ASC
`

func (q *Queries) ListEquipos(ctx context.Context) ([]Equipo, error) {
	rows, err := q.db.QueryContext(ctx, listEquipos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipo
	for rows.Next() {
		var i Equipo
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.FormacionActual,
			&i.EscudoUrl,
			&i.MejorJugador,
			&i.Valoracion,
			&i.PosicionTabla,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJugadoresByEquipo = `-- name: ListJugadoresByEquipo :many
SELECT id, equipo_id, nombre, posicion, fecha_nacimiento, media_general, altura, ritmo, tiro, pase, regate, defensa, fisico, goles, asistencias, foto_url FROM "jugadores"
WHERE "equipo_id" = $1
ORDER BY "media_general" DESC
`

func (q *Queries) ListJugadoresByEquipo(ctx context.Context, equipoID int32) ([]Jugadore, error) {
	rows, err := q.db.QueryContext(ctx, listJugadoresByEquipo, equipoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jugadore
	for rows.Next() {
		var i Jugadore
		if err := rows.Scan(
			&i.ID,
			&i.EquipoID,
			&i.Nombre,
			&i.Posicion,
			&i.FechaNacimiento,
			&i.MediaGeneral,
			&i.Altura,
			&i.Ritmo,
			&i.Tiro,
			&i.Pase,
			&i.Regate,
			&i.Defensa,
			&i.Fisico,
			&i.Goles,
			&i.Asistencias,
			&i.FotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartidos = `-- name: ListPartidos :many
SELECT id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, fecha, estado FROM "partidos"
ORDER BY "fecha" DESC
`

func (q *Queries) ListPartidos(ctx context.Context) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.ID,
			&i.EquipoLocalID,
			&i.EquipoVisitanteID,
			&i.GolesLocal,
			&i.GolesVisitante,
			&i.Fecha,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipo = `-- name: UpdateEquipo :one
UPDATE "equipos"
SET 
    "nombre" = COALESCE($2, "nombre"),
    "formacion_actual" = COALESCE($3, "formacion_actual"),
    "escudo_url" = COALESCE($4, "escudo_url"),
    "mejor_jugador" = COALESCE($5, "mejor_jugador"),
    "valoracion" = COALESCE($6, "valoracion"),
    "posicion_tabla" = COALESCE($7, "posicion_tabla")
WHERE "id" = $1
RETURNING id, nombre, formacion_actual, escudo_url, mejor_jugador, valoracion, posicion_tabla
`

type UpdateEquipoParams struct {
	ID              int32          `json:"id"`
	Nombre          string         `json:"nombre"`
	FormacionActual string         `json:"formacion_actual"`
	EscudoUrl       sql.NullString `json:"escudo_url"`
	MejorJugador    sql.NullInt32  `json:"mejor_jugador"`
	Valoracion      int16          `json:"valoracion"`
	PosicionTabla   int16          `json:"posicion_tabla"`
}

func (q *Queries) UpdateEquipo(ctx context.Context, arg UpdateEquipoParams) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, updateEquipo,
		arg.ID,
		arg.Nombre,
		arg.FormacionActual,
		arg.EscudoUrl,
		arg.MejorJugador,
		arg.Valoracion,
		arg.PosicionTabla,
	)
	var i Equipo
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FormacionActual,
		&i.EscudoUrl,
		&i.MejorJugador,
		&i.Valoracion,
		&i.PosicionTabla,
	)
	return i, err
}

const updateJugadorStats = `-- name: UpdateJugadorStats :one
UPDATE "jugadores"
SET 
    "goles" = "goles" + $2,
    "asistencias" = "asistencias" + $3
WHERE "id" = $1
RETURNING id, equipo_id, nombre, posicion, fecha_nacimiento, media_general, altura, ritmo, tiro, pase, regate, defensa, fisico, goles, asistencias, foto_url
`

type UpdateJugadorStatsParams struct {
	ID          int32 `json:"id"`
	Goles       int16 `json:"goles"`
	Asistencias int16 `json:"asistencias"`
}

func (q *Queries) UpdateJugadorStats(ctx context.Context, arg UpdateJugadorStatsParams) (Jugadore, error) {
	row := q.db.QueryRowContext(ctx, updateJugadorStats, arg.ID, arg.Goles, arg.Asistencias)
	var i Jugadore
	err := row.Scan(
		&i.ID,
		&i.EquipoID,
		&i.Nombre,
		&i.Posicion,
		&i.FechaNacimiento,
		&i.MediaGeneral,
		&i.Altura,
		&i.Ritmo,
		&i.Tiro,
		&i.Pase,
		&i.Regate,
		&i.Defensa,
		&i.Fisico,
		&i.Goles,
		&i.Asistencias,
		&i.FotoUrl,
	)
	return i, err
}

const updateResultadoPartido = `-- name: UpdateResultadoPartido :one
UPDATE "partidos"
SET 
    "goles_local" = $2,
    "goles_visitante" = $3,
    "estado" = $4
WHERE "id" = $1
RETURNING id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, fecha, estado
`

type UpdateResultadoPartidoParams struct {
	ID             int32  `json:"id"`
	GolesLocal     int16  `json:"goles_local"`
	GolesVisitante int16  `json:"goles_visitante"`
	Estado         string `json:"estado"`
}

func (q *Queries) UpdateResultadoPartido(ctx context.Context, arg UpdateResultadoPartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, updateResultadoPartido,
		arg.ID,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Estado,
	)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
		&i.Estado,
	)
	return i, err
}
