
CREATE TABLE IF NOT EXISTS "equipos" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"nombre" VARCHAR(100) NOT NULL UNIQUE,
	"formacion_actual" VARCHAR(10) NOT NULL DEFAULT '4-3-3',
	"escudo_url" VARCHAR(255),
	"mejor_jugador" INTEGER,
	"valoracion" SMALLINT NOT NULL CHECK (valoracion BETWEEN 1 AND 99),
	"posicion_tabla" SMALLINT NOT NULL CHECK (posicion_tabla > 0)
);

CREATE TABLE IF NOT EXISTS "jugadores" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"equipo_id" INTEGER NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"posicion" VARCHAR(10) NOT NULL CHECK (posicion IN ('POR', 'DEF', 'MED', 'DEL')),
	"fecha_nacimiento" DATE NOT NULL,
	"media_general" SMALLINT NOT NULL CHECK (media_general BETWEEN 1 AND 99),
	"altura" NUMERIC(3,2) NOT NULL,
	"ritmo" SMALLINT NOT NULL CHECK (ritmo BETWEEN 1 AND 99),
	"tiro" SMALLINT NOT NULL CHECK (tiro BETWEEN 1 AND 99),
	"pase" SMALLINT NOT NULL CHECK (pase BETWEEN 1 AND 99),
	"regate" SMALLINT NOT NULL CHECK (regate BETWEEN 1 AND 99),
	"defensa" SMALLINT NOT NULL CHECK (defensa BETWEEN 1 AND 99),
	"fisico" SMALLINT NOT NULL CHECK (fisico BETWEEN 1 AND 99),
	"goles" SMALLINT NOT NULL DEFAULT 0 CHECK (goles >= 0),
	"asistencias" SMALLINT NOT NULL DEFAULT 0 CHECK (asistencias >= 0),
	"foto_url" VARCHAR(255),
	CONSTRAINT fk_jugadores_equipo 
		FOREIGN KEY ("equipo_id") REFERENCES "equipos"("id") 
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "partidos" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"equipo_local_id" INTEGER NOT NULL,
	"equipo_visitante_id" INTEGER NOT NULL,
	"goles_local" SMALLINT NOT NULL DEFAULT 0 CHECK (goles_local >= 0),
	"goles_visitante" SMALLINT NOT NULL DEFAULT 0 CHECK (goles_visitante >= 0),
	"fecha" DATE NOT NULL,
	"estado" VARCHAR(40) NOT NULL CHECK (estado IN ('PENDIENTE', 'EN CURSO', 'FINALIZADO')),
	CONSTRAINT fk_partidos_equipo_local 
		FOREIGN KEY ("equipo_local_id") REFERENCES "equipos"("id") 
		ON DELETE RESTRICT,
	CONSTRAINT fk_partidos_equipo_visitante 
		FOREIGN KEY ("equipo_visitante_id") REFERENCES "equipos"("id") 
		ON DELETE RESTRICT,
	CONSTRAINT chk_equipos_distintos 
		CHECK ("equipo_local_id" != "equipo_visitante_id")
);

-- Constraint para relacionar el mejor jugador de la tabla equipos con la tabla jugadores
ALTER TABLE "equipos" 
ADD CONSTRAINT fk_equipos_mejor_jugador 
FOREIGN KEY ("mejor_jugador") REFERENCES "jugadores"("id") 
ON DELETE SET NULL;